<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-11T18:04:15Z" name="Default suite" finished-at="2025-02-11T18:04:36Z" duration-ms="21232">
    <groups>
    </groups>
    <test started-at="2025-02-11T18:04:15Z" name="Default test" finished-at="2025-02-11T18:04:36Z" duration-ms="21232">
      <class name="org.ee.test.TC_001LoginTest">
        <test-method is-config="true" signature="createReportGeneration()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:15Z" name="createReportGeneration" finished-at="2025-02-11T18:04:15Z" duration-ms="279" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createReportGeneration -->
        <test-method is-config="true" signature="startWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:16Z" name="startWeb" finished-at="2025-02-11T18:04:19Z" duration-ms="3135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWeb -->
        <test-method signature="loginTesWithInvalidData(java.lang.String, java.lang.String)[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:19Z" name="loginTesWithInvalidData" data-provider="getInValidLoginExcelSheetData" finished-at="2025-02-11T18:04:20Z" duration-ms="1724" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[akash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[akash]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://test-manage.eateasy.ae/users/employee_log] but found [https://test-manage.eateasy.ae/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://test-manage.eateasy.ae/users/employee_log] but found [https://test-manage.eateasy.ae/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.ee.test.TC_001LoginTest.loginTesWithInvalidData(TC_001LoginTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTesWithInvalidData -->
        <test-method is-config="true" signature="stopWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:20Z" name="stopWeb" finished-at="2025-02-11T18:04:21Z" duration-ms="257" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopWeb -->
        <test-method is-config="true" signature="startWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:21Z" name="startWeb" finished-at="2025-02-11T18:04:23Z" duration-ms="2399" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWeb -->
        <test-method signature="loginTesWithInvalidData(java.lang.String, java.lang.String)[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:23Z" name="loginTesWithInvalidData" data-provider="getInValidLoginExcelSheetData" finished-at="2025-02-11T18:04:24Z" duration-ms="1187" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[sathish]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sathish]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://test-manage.eateasy.ae/users/employee_log] but found [https://test-manage.eateasy.ae/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://test-manage.eateasy.ae/users/employee_log] but found [https://test-manage.eateasy.ae/]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at org.ee.test.TC_001LoginTest.loginTesWithInvalidData(TC_001LoginTest.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTesWithInvalidData -->
        <test-method is-config="true" signature="stopWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:24Z" name="stopWeb" finished-at="2025-02-11T18:04:25Z" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopWeb -->
        <test-method is-config="true" signature="startWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:25Z" name="startWeb" finished-at="2025-02-11T18:04:27Z" duration-ms="2324" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWeb -->
        <test-method signature="loginTestWithValidData(java.lang.String, java.lang.String)[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:27Z" name="loginTestWithValidData" data-provider="getValidLoginExcelSheetData" finished-at="2025-02-11T18:04:29Z" duration-ms="2319" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[ritesh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ritesh]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestWithValidData -->
        <test-method is-config="true" signature="stopWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:29Z" name="stopWeb" finished-at="2025-02-11T18:04:30Z" duration-ms="335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopWeb -->
        <test-method is-config="true" signature="startWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:30Z" name="startWeb" finished-at="2025-02-11T18:04:32Z" duration-ms="2240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startWeb -->
        <test-method signature="loginTestWithValidData(java.lang.String, java.lang.String)[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:32Z" name="loginTestWithValidData" data-provider="getValidLoginExcelSheetData" finished-at="2025-02-11T18:04:35Z" duration-ms="3291" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[akash]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[akash]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTestWithValidData -->
        <test-method is-config="true" signature="stopWeb()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:35Z" name="stopWeb" finished-at="2025-02-11T18:04:35Z" duration-ms="260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- stopWeb -->
        <test-method is-config="true" signature="flushReport()[pri:0, instance:org.ee.test.TC_001LoginTest@27912e3]" started-at="2025-02-11T18:04:35Z" name="flushReport" finished-at="2025-02-11T18:04:36Z" duration-ms="482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushReport -->
      </class> <!-- org.ee.test.TC_001LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
